apiVersion: apps/v1
kind: Deployment
metadata:
  name: xp-dotnet-sqlserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xp-dotnet-sqlserver
  template:
    metadata:
      labels:
        app: xp-dotnet-sqlserver
    spec:
      containers:
      - name: xp-dotnet-sqlserver
        image: xp-dotnet-sqlserver:latest
        imagePullPolicy: Never 
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: xp-dotnet-sqlserver-configmap
        env:
        - name: SQLSERVER_CONNECTION
          valueFrom:
            secretKeyRef:
              name: xp-dotnet-sqlserver-secrets
              key: SQLSERVER_CONNECTION
        # This given to us from Helm chart
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: xp-redis
              key: redis-password
        - name: KAFKA_SASL_USERNAME
          valueFrom:
            secretKeyRef:
              name: xp-dotnet-sqlserver-secrets
              key: KAFKA_SASL_USERNAME
        # This given to us from Helm chart
        - name: KAFKA_SASL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: xp-kafka-user-passwords
              key: client-passwords
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name