apiVersion: v1
kind: Secret
metadata:
  name: xp-dotnet-sqlserver-secrets
type: Opaque
data:
  KAFKA_SASL_USERNAME: dXNlcjE=
  SQLSERVER_CONNECTION: U2VydmVyPW1zc3FsLXNlcnZlci1tc3NxbC1sYXRlc3QuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbCwxNDMzO0RhdGFiYXNlPUFwcGxpY2F0aW9uRGI7VXNlciBJRD1zYTtQYXNzd29yZD1Ub3VnaHBhc3MxITtUcnVzdFNlcnZlckNlcnRpZmljYXRlPVRydWU7