apiVersion: v1
kind: Service
metadata:
  name: xp-dotnet-sqlserver-service
spec:
  selector:
    app: xp-dotnet-sqlserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer